apiVersion: v1
kind: Service
metadata:
  name: nfs-service-airflow-dags
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-airflow-dags
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service-airflow-logs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server-airflow-logs    
